version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel_pms_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotel123
      POSTGRES_DB: hotel_pms
    ports:
      - "5432:5432"
    volumes:
      - hotel_pgdata:/var/lib/postgresql/data

volumes:
  hotel_pgdata:
